/* BY: Bill Jiang DATE: 06/09/08 ECO: SS - 20080609.1 */

DEFINE INPUT PARAMETER i_i1 AS INTEGER.
DEFINE INPUT PARAMETER i_i2 AS INTEGER.
DEFINE OUTPUT PARAMETER o_c1 AS CHARACTER.

IF i_i1 <= 0 OR i_i2 <= 0 THEN DO:
   RETURN.
END.

o_c1 = STRING(TRUNCATE( i_i1 / i_i2 - 0.1, 0) + 1) .
