/* xxlu029.p - 应付帐凭证 Lookup UI                                         */
/* Copyright 1986-2009 QAD Inc., Carpinteria, CA, USA.                      */
/* All rights reserved worldwide.  This is an unpublished work.             */
/* $Revision: 1.71.1.2 $    */
/*V8:ConvertMode=NoConvert                                                  */
/********************************** History *********************************
 * $Revision: 1.2 $    admindmin                  DATE: 09/09/16  ECO: *XXXX*
 ****************************************************************************/

{mfdeclre.i}

&SCOPED-DEFINE BR-TITLE "应付帐凭证"

&SCOPED-DEFINE BR-NAME xx029
&SCOPED-DEFINE Q-DRAG-BACK-COL 1

&SCOPED-DEFINE Q-FIRST-TABLE ap_mstr
&SCOPED-DEFINE Q-FIRST-JOIN (ap_open = yes and ap_type = 'VO') 
&SCOPED-DEFINE Q-2ND-TABLE vo_mstr
&SCOPED-DEFINE Q-2ND-JOIN vo_ref = ap_ref 
&SCOPED-DEFINE Q-NUM-TABLES 2

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-1 b-1.ap_ref
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-1 ap_mstr.ap_ref
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-1 tt-ap_ref
&SCOPED-DEFINE BR-K-COL-LABEL-1 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-1 "参考"
&SCOPED-DEFINE BR-FIELD-TYPE-1 character
&SCOPED-DEFINE BR-FIELD-FRMT-1 FORMAT "x(10)"
&SCOPED-DEFINE BR-FIELD-WIDTH-1 11

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-2 b-2.vo_due_date
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-2 vo_mstr.vo_due_date
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-2 tt-vo_due_date
&SCOPED-DEFINE BR-K-COL-LABEL-2 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-2 "截止日期"
&SCOPED-DEFINE BR-FIELD-TYPE-2 date
&SCOPED-DEFINE BR-FIELD-FRMT-2 FORMAT "99/99/99"
&SCOPED-DEFINE BR-FIELD-WIDTH-2 9

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-3 b-2.vo_invoice
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-3 vo_mstr.vo_invoice
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-3 tt-vo_invoice
&SCOPED-DEFINE BR-K-COL-LABEL-3 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-3 "发票"
&SCOPED-DEFINE BR-FIELD-TYPE-3 character
&SCOPED-DEFINE BR-FIELD-FRMT-3 FORMAT "x(20)"
&SCOPED-DEFINE BR-FIELD-WIDTH-3 21

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-4 b-2.vo_disc_date
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-4 vo_mstr.vo_disc_date
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-4 tt-vo_disc_date
&SCOPED-DEFINE BR-K-COL-LABEL-4 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-4 "折扣日期"
&SCOPED-DEFINE BR-FIELD-TYPE-4 date
&SCOPED-DEFINE BR-FIELD-FRMT-4 FORMAT "99/99/99"
&SCOPED-DEFINE BR-FIELD-WIDTH-4 9

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-5 b-1.ap_curr
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-5 ap_mstr.ap_curr
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-5 tt-ap_curr
&SCOPED-DEFINE BR-K-COL-LABEL-5 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-5 "货币"
&SCOPED-DEFINE BR-FIELD-TYPE-5 character
&SCOPED-DEFINE BR-FIELD-FRMT-5 FORMAT "x(3)"
&SCOPED-DEFINE BR-FIELD-WIDTH-5 5

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-6 (ap_amt - vo_applied)
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-6 local-6
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-6 tt-local-6
&SCOPED-DEFINE BR-K-COL-LABEL-6 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-6 "未结金额"
&SCOPED-DEFINE BR-FIELD-TYPE-6 decimal
&SCOPED-DEFINE BR-FIELD-FRMT-6 FORMAT "->>,>>>,>>>.99"
&SCOPED-DEFINE BR-FIELD-WIDTH-6 15

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-7 b-1.ap_bank
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-7 ap_mstr.ap_bank
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-7 tt-ap_bank
&SCOPED-DEFINE BR-K-COL-LABEL-7 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-7 "银行"
&SCOPED-DEFINE BR-FIELD-TYPE-7 character
&SCOPED-DEFINE BR-FIELD-FRMT-7 FORMAT "x(2)"
&SCOPED-DEFINE BR-FIELD-WIDTH-7 5

&SCOPED-DEFINE BR-LOCAL-VAR-6 define variable local-6 as decimal format "->>,>>>,>>>.99" no-undo.
&SCOPED-DEFINE Q-NUM-FILT-VALS 7
&SCOPED-DEFINE BR-MAX-FIELD-WIDTH 21
&SCOPED-DEFINE BR-BROWSE-WIDTH 75
&SCOPED-DEFINE WHERE-CLAUSE (ap_vend = global_addr)
&SCOPED-DEFINE BR-INDEXED-FIELDS 1,3

{wbbr01.i &string-4 = 'LOOKUP'}
if c-application-mode <> 'WEB' then do:
   {lookup.i}
end.


