DEF VAR islogin AS LOGICAL.
islogin = NO.
DEFINE NEW SHARED VARIABLE usr AS CHARACTER LABEL "用户名".
DEFINE NEW SHARED VARIABLE pwd AS CHARACTER  CASE-SENSITIVE  LABEL "密码" FORMAT "x(16)".
DEFINE IMAGE logo
    FILE "04-1a.jpg"
    FROM X 4 Y 0
    SIZE-PIXELS 366 BY 283.
 

DEFINE FRAME a
   
    SKIP(2) SPACE(22)
     logo SKIP(2) SPACE(20)
    usr SPACE(16)
    pwd  BLANK SPACE(2) 
    SKIP(2)
    WITH WIDTH 90 SIDE-LABEL TITLE "条码系统" THREE-D CENTERED .

