DEF VAR islogin AS LOGICAL.
islogin = NO.
DEFINE NEW SHARED VARIABLE usr AS CHARACTER LABEL "用户名".
DEFINE NEW SHARED VARIABLE pwd AS CHARACTER  CASE-SENSITIVE  LABEL "密码" FORMAT "x(10)".
DEFINE IMAGE logo
    FILE "04-1a.jpg"
    FROM X 4 Y 0
    SIZE-PIXELS 200 BY 200.
 

DEFINE FRAME a
   
    SKIP(.5) SPACE(22)
     logo SKIP(1) SPACE(1)
    usr COLON 10
    pwd  COLON 10 
    SKIP(1)
    WITH WIDTH 30 SIDE-LABEL TITLE "条码系统" THREE-D CENTERED .





