/* xxlu030.p - 销售发票价格单 Lookup UI                                     */
/* Copyright 1986-2009 QAD Inc., Carpinteria, CA, USA.                      */
/* All rights reserved worldwide.  This is an unpublished work.             */
/* $Revision: 1.71.1.2 $    */
/*V8:ConvertMode=NoConvert                                                  */
/********************************** History *********************************
 * $Revision: 1.2 $    admindmin                  DATE: 09/11/16  ECO: *XXXX*
 ****************************************************************************/

{mfdeclre.i}

&SCOPED-DEFINE BR-TITLE "销售发票价格单"

&SCOPED-DEFINE BR-NAME xx030
&SCOPED-DEFINE Q-DRAG-BACK-COL 1

&SCOPED-DEFINE Q-FIRST-TABLE xxpi_mstr
&SCOPED-DEFINE Q-FIRST-FIELD-LIST (xxpi_list xxpi_part xxpi_um xxpi_curr xxpi_start)
&SCOPED-DEFINE Q-NUM-TABLES 1

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-1 b-1.xxpi_list
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-1 xxpi_mstr.xxpi_list
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-1 tt-xxpi_list
&SCOPED-DEFINE BR-K-COL-LABEL-1 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-1 "价格单"
&SCOPED-DEFINE BR-FIELD-TYPE-1 character
&SCOPED-DEFINE BR-FIELD-FRMT-1 FORMAT "x(8)"
&SCOPED-DEFINE BR-FIELD-WIDTH-1 9

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-2 b-1.xxpi_part
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-2 xxpi_mstr.xxpi_part
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-2 tt-xxpi_part
&SCOPED-DEFINE BR-K-COL-LABEL-2 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-2 "零件种类"
&SCOPED-DEFINE BR-FIELD-TYPE-2 character
&SCOPED-DEFINE BR-FIELD-FRMT-2 FORMAT "x(18)"
&SCOPED-DEFINE BR-FIELD-WIDTH-2 19

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-3 b-1.xxpi_um
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-3 xxpi_mstr.xxpi_um
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-3 tt-xxpi_um
&SCOPED-DEFINE BR-K-COL-LABEL-3 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-3 "计量单位"
&SCOPED-DEFINE BR-FIELD-TYPE-3 character
&SCOPED-DEFINE BR-FIELD-FRMT-3 FORMAT "x(2)"
&SCOPED-DEFINE BR-FIELD-WIDTH-3 9

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-4 b-1.xxpi_curr
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-4 xxpi_mstr.xxpi_curr
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-4 tt-xxpi_curr
&SCOPED-DEFINE BR-K-COL-LABEL-4 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-4 "货币"
&SCOPED-DEFINE BR-FIELD-TYPE-4 character
&SCOPED-DEFINE BR-FIELD-FRMT-4 FORMAT "x(3)"
&SCOPED-DEFINE BR-FIELD-WIDTH-4 5

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-5 b-1.xxpi_start
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-5 xxpi_mstr.xxpi_start
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-5 tt-xxpi_start
&SCOPED-DEFINE BR-K-COL-LABEL-5 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-5 "开始"
&SCOPED-DEFINE BR-FIELD-TYPE-5 date
&SCOPED-DEFINE BR-FIELD-FRMT-5 FORMAT "99/99/99"
&SCOPED-DEFINE BR-FIELD-WIDTH-5 9

&SCOPED-DEFINE Q-NUM-FILT-VALS 5
&SCOPED-DEFINE BR-MAX-FIELD-WIDTH 19
&SCOPED-DEFINE BR-BROWSE-WIDTH 51
&SCOPED-DEFINE WHERE-CLAUSE 
&SCOPED-DEFINE BR-INDEXED-FIELDS 1

{wbbr01.i &string-4 = 'LOOKUP'}
if c-application-mode <> 'WEB' then do:
   {lookup.i}
end.


