/* gplu950.p - 帐户代码 Lookup UI                                           */
/* Copyright 1986-2008 QAD Inc., Carpinteria, CA, USA.                      */
/* All rights reserved worldwide.  This is an unpublished work.             */
/* $Revision: 1.71.1.2 $    */
/*V8:ConvertMode=NoConvert                                                  */
/********************************** History *********************************
 * $Revision: 1.2 $    admindmin                  DATE: 08/05/22  ECO: *XXXX*
 ****************************************************************************/

{mfdeclre.i}

&SCOPED-DEFINE BR-TITLE "帐户代码"

&SCOPED-DEFINE BR-NAME gp950
&SCOPED-DEFINE Q-DRAG-BACK-COL 1

&SCOPED-DEFINE Q-FIRST-TABLE ac_mstr
&SCOPED-DEFINE Q-FIRST-FIELD-LIST (ac_code ac_desc ac_curr ac_active ac_type ac_fpos ac_fx_index ac_modl_only ac_stat_acc)
&SCOPED-DEFINE Q-NUM-TABLES 1

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-1 b-1.ac_code
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-1 ac_mstr.ac_code
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-1 tt-ac_code
&SCOPED-DEFINE BR-K-COL-LABEL-1 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-1 "帐户"
&SCOPED-DEFINE BR-FIELD-TYPE-1 character
&SCOPED-DEFINE BR-FIELD-FRMT-1 FORMAT "x(8)"
&SCOPED-DEFINE BR-FIELD-WIDTH-1 9

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-2 b-1.ac_desc
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-2 ac_mstr.ac_desc
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-2 tt-ac_desc
&SCOPED-DEFINE BR-K-COL-LABEL-2 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-2 "说明"
&SCOPED-DEFINE BR-FIELD-TYPE-2 character
&SCOPED-DEFINE BR-FIELD-FRMT-2 FORMAT "x(50)"
&SCOPED-DEFINE BR-FIELD-WIDTH-2 51

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-3 b-1.ac_curr
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-3 ac_mstr.ac_curr
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-3 tt-ac_curr
&SCOPED-DEFINE BR-K-COL-LABEL-3 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-3 "货币"
&SCOPED-DEFINE BR-FIELD-TYPE-3 character
&SCOPED-DEFINE BR-FIELD-FRMT-3 FORMAT "x(3)"
&SCOPED-DEFINE BR-FIELD-WIDTH-3 5

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-4 b-1.ac_active
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-4 MFC_LOGICAL
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-4 tt-ac_active
&SCOPED-DEFINE BR-K-COL-LABEL-4 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-4 "有效的"
&SCOPED-DEFINE BR-FIELD-TYPE-4 logical
&SCOPED-DEFINE BR-FIELD-WIDTH-4 7

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-5 b-1.ac_type
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-5 ac_mstr.ac_type
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-5 tt-ac_type
&SCOPED-DEFINE BR-K-COL-LABEL-5 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-5 "类型"
&SCOPED-DEFINE BR-FIELD-TYPE-5 character
&SCOPED-DEFINE BR-FIELD-FRMT-5 FORMAT "x(1)"
&SCOPED-DEFINE BR-FIELD-WIDTH-5 5

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-6 b-1.ac_fpos
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-6 ac_mstr.ac_fpos
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-6 tt-ac_fpos
&SCOPED-DEFINE BR-K-COL-LABEL-6 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-6 "格式位置"
&SCOPED-DEFINE BR-FIELD-TYPE-6 integer
&SCOPED-DEFINE BR-FIELD-FRMT-6 FORMAT ">>>>>9"
&SCOPED-DEFINE BR-FIELD-WIDTH-6 9

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-7 b-1.ac_fx_index
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-7 ac_mstr.ac_fx_index
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-7 tt-ac_fx_index
&SCOPED-DEFINE BR-K-COL-LABEL-7 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-7 "货币换算索引"
&SCOPED-DEFINE BR-FIELD-TYPE-7 character
&SCOPED-DEFINE BR-FIELD-FRMT-7 FORMAT "x(1)"
&SCOPED-DEFINE BR-FIELD-WIDTH-7 13

&SCOPED-DEFINE Q-NUM-FILT-VALS 9
&SCOPED-DEFINE BR-MAX-FIELD-WIDTH 51
&SCOPED-DEFINE BR-BROWSE-WIDTH 99
&SCOPED-DEFINE WHERE-CLAUSE ac_active = yes
&SCOPED-DEFINE BR-INDEXED-FIELDS 1,2,3,4,5,6

{wbbr01.i &string-4 = 'LOOKUP'}
if c-application-mode <> 'WEB' then do:
   {lookup.i}
end.


