RELEASE b_co_mstr.
         RELEASE b_tr_hist.
         RELEASE b_ld_det.
         RELEASE b_loc_mstr.
         RELEASE b_usrh_hist.
         RELEASE b_bf_det.
         RELEASE po_mstr.
         RELEASE so_mstr.
         RELEASE wo_mstr.
         RELEASE ABS_mstr.
         RELEASE pod_det.
         RELEASE sod_det.
         RELEASE wod_det.
         RELEASE B_SHP_WKFL.
