SESSION:DATE-FORMAT = "dmy".
INPUT FROM d:\i\wrk\pt.xp.in.
REPEAT:
    CREATE pt_mstr.
    IMPORT DELIMITER ","
       pt_part
       pt_desc1
       pt_desc2
       pt_um
       pt__qad13
       pt__qad12
       pt_draw
       pt_prod_line
       pt_group
       pt_part_type
       pt_status
       pt_abc
       pt_iss_pol
       pt_phantom
       pt_loc
       pt__qad01
       pt__qad02
       pt_abc_amt
       pt__qad03
       pt__qad04
       pt_avg_int
       pt__qad05
       pt_cyc_int
       pt__qad06
       pt__qad07
       pt__qad08
       pt_ms
       pt_plan_ord
       pt_mrp
       pt_ord_pol
       pt_ord_qty
       pt_ord_per
       pt_sfty_stk
       pt_sfty_time
       pt_rop
       pt_buyer
       pt_vend
       pt__qad09
       pt_pm_code
       pt_mfg_lead
       pt_pur_lead
       pt_insp_rqd
       pt_insp_lead
       pt_cum_lead
       pt_ord_min
       pt_ord_max
       pt_ord_mult
       pt_yield_pct
       pt__qad16
       pt_setup
       pt_setup_ll
       pt_run_ll
       pt_run
       pt_price
       pt_xmtl_tl
       pt_xlbr_tl
       pt_xbdn_tl
       pt_xsub_tl
       pt_xmtl_ll
       pt_xlbr_ll
       pt_xbdn_ll
       pt_xsub_ll
       pt_xtot_cur
       pt_cur_date
       pt_xmtl_stdtl
       pt_xlbr_stdtl
       pt_xbdn_stdtl
       pt_xsub_stdtl
       pt_xtot_std
       pt_std_date
       pt_ll_code
       pt_abc_qty
       pt__qad10
       pt__qad11
       pt_routing
       pt_lot_ser
       pt_timefence
       pt_xmtl_stdll
       pt_xlbr_stdll
       pt_xbdn_stdll
       pt_xsub_stdll
       pt_rev
       pt_last_eco
       pt__qad15
       pt__qad17
       pt_qc_lead
       pt_auto_lot
       pt_assay
       pt_batch
       pt__qad14
       pt_user3
       pt_user1
       pt_user2
       pt_net_wt
       pt_net_wt_um
       pt_size
       pt_size_um
       pt_taxable
       pt_taxc
       pt_rollup
       pt_xovh_ll
       pt_xovh_tl
       pt_xovh_stdll
       pt_xovh_stdtl
       pt_site
       pt_shelflife
       pt_critical
       pt_sngl_lot
       pt_upc
       pt_hazard
       pt_added
       pt__chr01
       pt__chr02
       pt__chr03
       pt__chr04
       pt__chr05
       pt__chr06
       pt__chr07
       pt__chr08
       pt__chr09
       pt__chr10
       pt__dte01
       pt__dte02
       pt__dec01
       pt__dec02
       pt__log01
       pt__log02
       pt__qad18
       pt__qad21
       pt__qad19
       pt__qad20
       pt_length
       pt_height
       pt_width
       pt_dim_um
       pt_pkg_code
       pt_network
       pt_ll_drp
       pt_fr_class
       pt_spec_hdlg
       pt_bom_code
       pt_loc_type
       pt_transtype
       pt_cover
       pt_unit_isb
       pt_article
       pt_po_site
       pt_ship_wt
       pt_ship_wt_um
       pt_formula
       pt_dea
       pt__qad26
       pt__qad22
       pt__qad25
       pt__qad24
       pt__qad23
       pt_comm_code
       pt_inst_call
       pt_sys_type
       pt_tariff
       pt_origin
       pt_sttr
       pt_mfg_mtbf
       pt_mfg_mttr
       pt_fru
       pt_ven_warr
       pt_svc_group
       pt_svc_type
       pt_mtbf
       pt_mttr
       pt_isb
       pt_pvm_days
       pt_warr_cd
       pt_mod_date
       pt_userid
       pt_obs_date
       pt_pvm_bom
       pt_pvm_route
       pt_pvm_um
       pt_rp_bom
       pt_rp_route
       pt_rp_vendor
       pt_rctpo_status
       pt_rollup_id
       pt_spec_grav
       pt_joint_type
       pt_mfg_pct
       pt_pur_pct
       pt_drp_pct
       pt_pou_code
       pt_wks_avg
       pt_wks_max
       pt_wks_min
       pt_pick_logic
       pt_fiscal_class
       pt_dsgn_grp
       pt_drwg_loc
       pt_ecn_rev
       pt_drwg_size
       pt_model
       pt_repairable
       pt_rctwo_status
       pt_lot_grp
       pt_rctpo_active
       pt_rctwo_active
       pt_break_cat
       pt_fsc_code
       pt_trace_active
       pt_trace_detail
       pt_pm_mrp
       pt_ins_call_type
       pt_ins_bom
       pt_ins_route
       pt_promo
       pt_meter_interval
       pt_meter_um
       pt_wh
       pt_btb_type
       pt_cfg_type
       pt_app_owner
       pt_op_yield
       pt_run_seq1
       pt_run_seq2
       pt_atp_enforcement
       pt_atp_family
       pt_domain.
END.