/* yybr002.p - 移仓单 Browse UI                                             */
/* Copyright 1986-2005 QAD Inc., Carpinteria, CA, USA.                      */
/* All rights reserved worldwide.  This is an unpublished work.             */
/* $Revision: 1.71.1.5 $    */
/*V8:ConvertMode=NoConvert                                                  */
/********************************** History *********************************
 ****************************************************************************/

{mfdeclre.i}

&SCOPED-DEFINE BR-TITLE "移仓单"

&SCOPED-DEFINE BR-NAME yy002
&SCOPED-DEFINE Q-DRAG-BACK-COL 1

&SCOPED-DEFINE Q-FIRST-TABLE xxtl_det
&SCOPED-DEFINE Q-FIRST-FIELD-LIST (xxtl_nbr xxtl_site xxtl_site1 xxtl_part xxtl_model xxtl_loc_fr xxtl_loc_to xxtl_qty_req xxtl_status xxtl_type)
&SCOPED-DEFINE Q-NUM-TABLES 1

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-1 b-1.xxtl_nbr
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-1 xxtl_det.xxtl_nbr
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-1 tt-xxtl_nbr
&SCOPED-DEFINE BR-K-COL-LABEL-1 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-1 "移仓单"
&SCOPED-DEFINE BR-FIELD-TYPE-1 character
&SCOPED-DEFINE BR-FIELD-FRMT-1 FORMAT "X(16)"
&SCOPED-DEFINE BR-FIELD-WIDTH-1 17

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-2 b-1.xxtl_site
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-2 xxtl_det.xxtl_site
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-2 tt-xxtl_site
&SCOPED-DEFINE BR-K-COL-LABEL-2 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-2 "移出地点"
&SCOPED-DEFINE BR-FIELD-TYPE-2 character
&SCOPED-DEFINE BR-FIELD-FRMT-2 FORMAT "X(8)"
&SCOPED-DEFINE BR-FIELD-WIDTH-2 9

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-3 b-1.xxtl_site1
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-3 xxtl_det.xxtl_site1
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-3 tt-xxtl_site1
&SCOPED-DEFINE BR-K-COL-LABEL-3 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-3 "移入地点"
&SCOPED-DEFINE BR-FIELD-TYPE-3 character
&SCOPED-DEFINE BR-FIELD-FRMT-3 FORMAT "X(8)"
&SCOPED-DEFINE BR-FIELD-WIDTH-3 9

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-4 b-1.xxtl_part
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-4 xxtl_det.xxtl_part
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-4 tt-xxtl_part
&SCOPED-DEFINE BR-K-COL-LABEL-4 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-4 "零件"
&SCOPED-DEFINE BR-FIELD-TYPE-4 character
&SCOPED-DEFINE BR-FIELD-FRMT-4 FORMAT "X(18)"
&SCOPED-DEFINE BR-FIELD-WIDTH-4 19

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-5 b-1.xxtl_model
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-5 xxtl_det.xxtl_model
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-5 tt-xxtl_model
&SCOPED-DEFINE BR-K-COL-LABEL-5 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-5 "机型"
&SCOPED-DEFINE BR-FIELD-TYPE-5 character
&SCOPED-DEFINE BR-FIELD-FRMT-5 FORMAT "X(8)"
&SCOPED-DEFINE BR-FIELD-WIDTH-5 9

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-6 b-1.xxtl_loc_fr
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-6 xxtl_det.xxtl_loc_fr
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-6 tt-xxtl_loc_fr
&SCOPED-DEFINE BR-K-COL-LABEL-6 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-6 "移出库位"
&SCOPED-DEFINE BR-FIELD-TYPE-6 character
&SCOPED-DEFINE BR-FIELD-FRMT-6 FORMAT "X(8)"
&SCOPED-DEFINE BR-FIELD-WIDTH-6 9

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-7 b-1.xxtl_loc_to
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-7 xxtl_det.xxtl_loc_to
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-7 tt-xxtl_loc_to
&SCOPED-DEFINE BR-K-COL-LABEL-7 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-7 "移入库位"
&SCOPED-DEFINE BR-FIELD-TYPE-7 character
&SCOPED-DEFINE BR-FIELD-FRMT-7 FORMAT "X(8)"
&SCOPED-DEFINE BR-FIELD-WIDTH-7 9

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-8 b-1.xxtl_qty_req
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-8 xxtl_det.xxtl_qty_req
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-8 tt-xxtl_qty_req
&SCOPED-DEFINE BR-K-COL-LABEL-8 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-8 "需求量"
&SCOPED-DEFINE BR-FIELD-TYPE-8 decimal
&SCOPED-DEFINE BR-FIELD-FRMT-8 FORMAT ">>,>>9.99"
&SCOPED-DEFINE BR-FIELD-WIDTH-8 10

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-9 b-1.xxtl_status
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-9 xxtl_det.xxtl_status
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-9 tt-xxtl_status
&SCOPED-DEFINE BR-K-COL-LABEL-9 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-9 "状态"
&SCOPED-DEFINE BR-FIELD-TYPE-9 character
&SCOPED-DEFINE BR-FIELD-FRMT-9 FORMAT "X(1)"
&SCOPED-DEFINE BR-FIELD-WIDTH-9 5

&SCOPED-DEFINE Q-BROWSE-DISP-EXPR-10 b-1.xxtl_type
&SCOPED-DEFINE Q-BROWSE-DEF-EXPR-10 xxtl_det.xxtl_type
&SCOPED-DEFINE TT-Q-BROWSE-DEF-EXPR-10 tt-xxtl_type
&SCOPED-DEFINE BR-K-COL-LABEL-10 COLUMN-LABEL
&SCOPED-DEFINE BR-COLUMN-LABEL-10 "类型"
&SCOPED-DEFINE BR-FIELD-TYPE-10 character
&SCOPED-DEFINE BR-FIELD-FRMT-10 FORMAT "X(1)"
&SCOPED-DEFINE BR-FIELD-WIDTH-10 5

&SCOPED-DEFINE Q-NUM-FILT-VALS 10
&SCOPED-DEFINE BR-MAX-FIELD-WIDTH 19
&SCOPED-DEFINE BR-BROWSE-WIDTH 101
&SCOPED-DEFINE WHERE-CLAUSE 
&SCOPED-DEFINE BR-INDEXED-FIELDS 1

{wbbr01.i}
if c-application-mode <> 'WEB' then do:
   {browse.i}
end.


