DEFINE INPUT PARAMETER cimf AS CHARACTER .
DEFINE INPUT PARAMETER part AS CHARACTER .
DEFINE INPUT PARAMETER qty AS CHARACTER .
DEFINE INPUT PARAMETER effdate AS CHARACTER .
DEFINE INPUT PARAMETER order AS CHARACTER .
DEFINE INPUT PARAMETER site1 AS CHARACTER .
DEFINE INPUT PARAMETER loc1 AS CHARACTER .
DEFINE INPUT PARAMETER lot1 AS CHARACTER .
DEFINE INPUT PARAMETER ref1 AS CHARACTER .
DEFINE INPUT PARAMETER site2 AS CHARACTER .
DEFINE INPUT PARAMETER loc2 AS CHARACTER .

OUTPUT TO VALUE(cimf) APPEND .
PUT UNFORMATTED 
    "@@batchload iclotr04.p" SKIP 
    "~"" part "~"" SKIP
    qty " " effdate  " "
    "~"" order "~""
    SKIP(1)
    "~"" site1 "~" ~"" loc1 "~" ~"" lot1 "~" ~"" ref1 "~"" SKIP
    "~"" site2 "~" ~"" loc2 "~"" SKIP
    "." SKIP
    "." SKIP
    "@@end" SKIP .
OUTPUT CLOSE .

                


