/* SS - 081211.1 By: Bill Jiang */

DEFINE INPUT-OUTPUT PARAMETER input1 AS CHARACTER.
DEFINE INPUT PARAMETER input2 AS CHARACTER.

DEFINE VARIABLE i1 AS INTEGER.
DEFINE VARIABLE i2 AS INTEGER.

IF LENGTH(input2) = 0 THEN RETURN.

i1 = LENGTH(input1).
DO  i2 = i1 TO 1 BY -1:
   IF SUBSTRING(input1, i2, MINIMUM(LENGTH(input2), i1 - i2 + 1)) = input2 THEN DO:
      input1 = SUBSTRING(input1, i2 + 1, i1 - i2).
      RETURN.
   END.
END.
