{mfdeclre.i}
{bcdeclre2.i}

DEFINE INPUT PARAMETER bccode LIKE b_co_code.
DEFINE OUTPUT PARAMETER active AS LOGICAL.
DEFINE OUTPUT PARAMETER bcpart LIKE pt_part.
DEFINE OUTPUT PARAMETER bcqty AS DECIMAL FORMAT "->>,>>>.99".
DEFINE OUTPUT PARAMETER bcsite LIKE b_co_site.
DEFINE OUTPUT PARAMETER bcloc LIKE b_co_loc.
DEFINE OUTPUT PARAMETER bclot LIKE b_co_lot.
DEFINE OUTPUT PARAMETER bcstatus LIKE b_co_status.


DEFINE VARIABLE vend AS CHARACTER FORMAT "x(1)".
DEFINE VARIABLE syear AS CHAR.
DEFINE VARIABLE len AS INTEGER.
DEFINE VARIABLE posi AS INTEGER.


bccode = TRIM(bccode).
len = LENGTH(bccode).

active = FALSE.
DO ON ERROR UNDO:


    FIND FIRST b_co_mstr NO-LOCK WHERE b_co_code = bccode AND b_co_status EQ "DISABLE"  NO-ERROR.
    IF AVAILABLE b_co_mstr THEN DO:
        active = FALSE.
        LEAVE.
    END.

    
    FIND FIRST b_co_mstr NO-LOCK WHERE b_co_code = bccode AND b_co_status NE "DISABLE"  NO-ERROR.
    IF AVAILABLE b_co_mstr THEN DO:  /*this statment is to identify if the barcode is existed ,if yes then it's status is actived*/
            bcpart = b_co_part.
            bcqty = b_co_qty_cur.
            bclot = b_co_lot.
            bcsite = b_co_site.
            bcloc = b_co_loc.
            bcstatus = b_co_status.
            active = YES.
    END.
    ELSE DO:    /*if the barcode doesn't exist , maybe it is generated by supplier, so verify if it is fitted to the rule*/
                IF len <= 12 THEN LEAVE.  /*if it's length less than 12 , it prove it is not a generated barcode*/
                bcpart = SUBSTRING(bccode,1,len - 12).
                FIND FIRST pt_mstr NO-LOCK WHERE pt_part = bcpart NO-ERROR.
                IF NOT AVAILABLE pt_mstr THEN DO:     /*item number exist*/
                     active = NO.
                END.
                ELSE DO:
                    bcpart = SUBSTRING(bccode,1,len - 12).
                    bcqty = int(SUBSTRING(bccode, len - 6 , 4)).
                    bcstatus = "MAT-CRE".
                    active = YES.

                    CREATE b_co_mstr.
                    ASSIGN
                         b_co_code = bccode
                         b_co_part = bcpart 
                         b_co_um = ""
                         b_co_lot = ""
                         b_co_status = bcstatus
                         b_co_desc1 =""
                         b_co_desc2 =  ""
                         b_co_qty_ini = bcqty
                         b_co_qty_cur =  bcqty
                         b_co_qty_std  = bcqty
                         b_co_ser = 0
                         b_co_ref = ""
                         b_co_site = ""
                         b_co_loc = ""
                         b_co_format ="".
                END.
    END.

END.

                     

